// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsxtbrzeurbjyaabhbss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzeHRicnpldXJianlhYWJoYnNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NzE2MTQsImV4cCI6MjA1MjI0NzYxNH0.SNCZ-QkkG7tX2ftWph2h6t8tLcQL0qz7S78l3t3cFNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);